import Head from 'next/head'
import Navbar from "../components/Navbar.js"
import FirstPage from "../components/FirstPage.js"
import SecondPage from "../components/SecondPage.js"
import ThirdPage from "../components/ThirdPage.js"
import FourthPage from "../components/FourthPage.js"
import FifthPage from "../components/FifthPage.js"
import SixPage from "../components/SixPage.js"
import SevenPage from "../components/SevenPage.js"
import Footer from "../components/Footer.js"

export default function Home() {
  return (
		<div >
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main >
				<Navbar />
                <FirstPage />
                <SecondPage />
                <ThirdPage />
                <FourthPage />
                <FifthPage />
                <SixPage />
                <SevenPage />
                <Footer />
			</main>

			<footer></footer>
		</div>
	);
}
